// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface InvokeResult {
  status: number
  headers: { [key: string]: string[] }
  body: string
}

export interface PlatformInfoDTO {
  mode: string
  streamBase: string
  version: string
  commit: string
  buildDate: string
}

export function PlatformInfo(): Promise<PlatformInfoDTO>;

export function Invoke(method: string, path: string, headers: { [key: string]: string }, body: string): Promise<InvokeResult>;
