// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function PlatformInfo() {
  return window['go']['desktop']['Bridge']['PlatformInfo']();
}

export function Invoke(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['Bridge']['Invoke'](arg1, arg2, arg3, arg4);
}
