package web

import (
	"embed"
	"io/fs"
)

// embeddedDist is generated by the frontend build. The production binary owns
// these files; no runtime Node.js or external asset directory is required.
//
//go:embed all:dist
var embeddedDist embed.FS

func Embedded() (fs.FS, error) {
	return fs.Sub(embeddedDist, "dist")
}
